version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    build:
      context: ./
      dockerfile: pg.dockerfile
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
