version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
