[env]
TEST_URL = "postgres://root:password@"
TEST_DATABASE = "testdb"


[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
comand = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.food-flow]
dependences = [
    "format",
    "build",
    "test"
]

[tasks.setup]
script_runner = "@rust"
script = [
'''
//! ```cargo
//! [dependencies]
//! diesel = { version = "1.4.5", features = ["postgres"] }
extern crate diesel;

use diesel::prelude::*;
use diesel::pg::PgConnection;

fn main() {
    let postgres_url = "postgres://root:password@localhost:5432/postgres";
    let db_url = "postgres://root:password@localhost:5432/testdb";
    let conn =
        PgConnection::establish(&postgres_url).expect("Could not connect to database on test run, exiting");
    let query = diesel::sql_query("CREATE DATABASE testdb");

    query
        .execute(&conn)
        .expect("Could not create database testdb, exiting");
}
'''
]

[tasks.teardown]
script_runner = "@rust"
script = [
'''
//! ```cargo
//! [dependencies]
//! diesel = { version = "1.4.5", features = ["postgres"] }
extern crate diesel;

use diesel::prelude::*;
use diesel::pg::PgConnection;

fn main() {
    let postgres_url = "postgres://root:password@localhost:5432/postgres";
    let conn =
        PgConnection::establish(&postgres_url).expect("Could not connect to database, exiting");


    let query = diesel::sql_query("DROP DATABASE IF EXISTS testdb WITH (FORCE)");

    query
        .execute(&conn)
        .expect("Failure dropping database testdb, exiting");
}
'''
]


